src/Entity/Post.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private $body;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post")
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): void
    {
        $this->body = $body;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): void
    {
        $this->created_at = $created_at;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already'form' => $form->createView(),'form' => $form->createView(),'form' => $form->createView(), changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->body;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => '',
            ])
            ->add('body', TextareaType::class, [
                'label' => '',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Form\PostType;
use App\Repository\PostRepository;
use Cocur\Slugify\Slugify;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PostsController.
 *
 * @Route ("/posts")
 */
class PostsController extends AbstractController
{
    /**
     * @var PostRepository
     */
    private $postRepository;

    public function __construct(PostRepository $postRepository)
    {
        $this->postRepository = $postRepository;
    }

    /**
     * @Route("/", name="blog_posts")
     *
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request, PaginatorInterface $paginator)
    {
        $posts = $this->postRepository->findBy([], ['id' => 'DESC']);

        $pagination = $paginator->paginate(
            $posts,
            $request->query->getInt('page', 1),
            3
        );
        $img = rand(1, 3);

        return $this->render('posts/index.html.twig', [
            'posts' => $pagination,
            'img' => $img,
        ]);
    }

    /**
     * @Route("/new", name="new_blog_post")
     *
     * @param Request $request
     * @param Slugify $slugify
     * @return Response
     */
    public function addPost(Request $request, Slugify $slugify): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setSlug($slugify->slugify($post->getTitle()));
            $post->setCreatedAt(new \DateTime());

            $em = $this->getDoctrine()->getManager();
            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute('blog_posts');
        }

        return $this->render('posts/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="blog_post_edit")
     *
     * @param Post $post
     * @param Request $request
     * @param Slugify $slugify
     * @return RedirectResponse|Response
     */
    public function edit(Post $post, Request $request, Slugify $slugify)
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setSlug($slugify->slugify($post->getTitle()));

            $em = $this->getDoctrine()->getManager();
            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute('blog_posts', [
                'slug' => $post->getSlug(),
            ]);
        }

        return $this->render('posts/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}/delete", name="blog_post_delete")
     *
     * @param Post $post
     * @return RedirectResponse
     */
    public function delete(Post $post)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($post);
        $em->flush();

        return $this->redirectToRoute('blog_posts');
    }

    /**
     * @Route("/search", name="blog_search")
     *
     * @param Request $request
     * @return Response
     */
    public function search(Request $request)
    {
        $query = $request->query->get('q');
        $posts = $this->postRepository->searchByQuery($query);

        return $this->render('posts/query_post.html.twig', [
            'posts' => $posts,
        ]);
    }

    /**
     * @Route("/{slug}", methods={"GET", "POST"}, name="blog_show")
     *
     * @param Post $post
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function commentNew(Post $post, Request $request)
    {
        $comment = new Comment();
        $comment->setUsers($this->getUser());
        $post->addComment($comment);

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        $img = rand(1, 3);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($comment);
            $em->flush();

            return $this->redirectToRoute('blog_show', ['slug' => $post->getSlug()]);
        }

        return $this->render('posts/show.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
            'img' => $img,
        ]);
    }

    /*
     * @Route("/{slug}/comment/{id}/delete", name="comment_delete", methods={"GET", "DELETE"})
     *
    public function deleteComment(Post $post, Request $request, Comment $comment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('blog_show', ['slug' => $post->getSlug()]);
    }

    /**
     * @Route("{slug}/comment/{id}/edit", name="comment_edit", methods={"GET","POST"})
     *
     * @param Request $request
     * @param Comment $comment
     * @return Response
     *
    public function editComment(Post $post, Request $request, Comment $comment): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('blog_show', ['slug' => $post->getSlug()]);
        }

        return $this->render('posts/show.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }
    */

    /*
     * @Route("/posts/{slug}", name="blog_show")
     *
     * @return Response

    public function post(Post $post)
    {
        return $this->render('posts/1show.html.twig', [
            'post' => $post,
        ]);
    }*/
}

templates/posts/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Blog{% endblock %}
{% block content %}
    <div class="content">
        <div class="container">
            <!--<form class="form-inline my-2 my-lg-0" action="{{ path('blog_search') }}" method="get">
                <input class="form-control mr-sm-2" type="search" aria-label="Search" name="q">
                <button class="btn btn-default my-2 my-sm-0" type="submit">Поиск</button>
            </form>-->
            <div class="content-grids">
                <div class="col-md-8 content-main">
                    <div class="content-grid">
                        {% for post in posts %}
                            <div class="content-grid-info">
                                <img src="/blog/images/post{{ img }}.jpg" alt=""/>
                                <div class="post-info">
                                    <h4><a href="{{ path('blog_show', {'slug': post.slug}) }}">Post</a>{{ post.getCreatedAt() | date("m/d/Y") }}</h4>
                                    <p>{{ post.title }}</p>
                                    <a href="{{ path('blog_show', {'slug': post.slug}) }}"><span></span>READ MORE</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-4 content-right">
                    <div class="recent">
                        <h3>RECENT POSTS</h3>
                        <ul>
                            <li><a href="#">Aliquam tincidunt mauris</a></li>
                            <li><a href="#">Vestibulum auctor dapibus  lipsum</a></li>
                            <li><a href="#">Nunc dignissim risus consecu</a></li>
                            <li><a href="#">Cras ornare tristiqu</a></li>
                        </ul>
                    </div>
                    <div class="comments">
                        <h3>RECENT COMMENTS</h3>
                        <ul>
                            <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                            <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                            <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                    <div class="archives">
                        <h3>ARCHIVES</h3>
                        <ul>
                            <li><a href="#">October 2013</a></li>
                            <li><a href="#">September 2013</a></li>
                            <li><a href="#">August 2013</a></li>
                            <li><a href="#">July 2013</a></li>
                        </ul>
                    </div>
                    <div class="categories">
                        <h3>CATEGORIES</h3>
                        <ul>
                            <li><a href="#">Vivamus vestibulum nulla</a></li>
                            <li><a href="#">Integer vitae libero ac risus e</a></li>
                            <li><a href="#">Vestibulum commo</a></li>
                            <li><a href="#">Cras iaculis ultricies</a></li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <a href="{{ path('new_blog_post') }}">Создать</a>
            <div class="col-sm-12 col-md-5" id="getTotalItemCount">
                Total items: {{ posts.getTotalItemCount }}
            </div>
            <div class="col-sm-12 col-md-7">
                <div class="dataTables_paginate paging_simple_numbers" id="knp_pagination_render">
                    {{ knp_pagination_render(posts) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create post{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_row(form.title) }}
    {{ form_row(form.body, { 'attr': {
        'rows' : '20',
        'cols' : '40' }}) }}
    <small class="d-block text-right mt-3">
        <button class="btn btn-default" type="submit">Submit</button>
    </small>
    {{ form_end(form) }}
{% endblock %}

templates/posts/query_post.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search result{% endblock %}

{% block body %}
    {% for post in posts %}
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <a href="{{ path('blog_show', {slug: post.slug}) }}">{{ post.title }}</a><
                {{ post.body | slice(0, 255) ~ '...'  }}
            </p>
        </div>
    {% endfor %}
    <small class="d-block align-text-bottom mt-3">
        <a href="{{ path('blog_posts') }}">Home</a>
    </small>
{% endblock %}

templates/posts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post{% endblock %}

{% block body %}
	<div class="single">
		<div class="container">
			<div class="col-md-8 single-main">
				<div class="single-grid">
					<p><h4>{{ post.title }}</h4></p>
					<img src="/blog/images/post{{ img }}.jpg" alt=""/>
					<p>{{ post.body }}</p>
					<span>{{ post.getCreatedAt() | date("m/d/Y") }}</span>
					<br>
					<br>
					<a href="{{ path('blog_post_edit', {'slug': post.slug}) }}" class="btn-primary">Edit</a>&nbsp;
					<a href="{{ path('blog_post_delete', {'slug': post.slug}) }}" class="btn-danger">Delete</a>&nbsp;
					<a href="{{ path('blog_posts') }}" class="btn-default">Home</a>
				</div>
				<ul class="comment-list">
					<h5 class="post-author_head">Written by <a href="#" title="Posts by user.name" rel="author">user</a></h5>
					<li><img src="/blog/images/avatar.png" class="img-responsive" alt="">
						<div class="desc">
							<p>View all posts by: <a href="#" title="Posts by user" rel="author">user</a></p>
						</div>
						<div class="clearfix"></div>
					</li>
				</ul>
				<ul class="comment-list">
					{%  for comment in post.comments %}
						{% if comment.comment != null %}	<li>
								<div class="desc">
									<p>{{ comment.comment }}</p>
									<br>
									<tr>
										<td>{{ comment.users }} - </td>
										<td>{{ comment.createdAt ? comment.createdAt|date('Y-m-d') : '' }}</td>&nbsp;
										{% if (comment.createdAt != comment.updatedAt) %}
											<td>{{ comment.updatedAt ? comment.updatedAt|date('Y-m-d') : '' }}</td>&nbsp;
										{% endif %}
										{#<td>
											<a href="{{ path('comment_edit', {'slug': post.slug, 'id': comment.id}) }}" class="btn-primary">Edit</a>&nbsp;
											<a href="{{ path('comment_delete', {'slug': post.slug, 'id': comment.id}) }}" class="btn-danger">Delete</a>&nbsp;
										</td>#}
									</tr>
								</div>
							</li>
						{% endif %}
					{% endfor %}
				</ul>
				<div class="content-form">
					<h3>Leave a comment</h3>
						{{ form_start(form) }}
							{{ form_row(form.comment) }}
						<button type="submit" class="btn btn-primary">Send</button>
						{{ form_end(form) }}
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
{% endblock %}